### ISSUE TITLE
Successful creation message

### ISSUE THREAD

**Issue by afrubin** [FowlerLab/mavedb#49]
The creation message when a Score Set is created is unintuitive. It should clarify that "procesing" means that scores and counts are still being entered into the database. Otherwise it seems like it worked properly but there's no counts and scores.

**Comment by daniaki** [comment]
How does this read?

Successfully created a new Score Set, which has been assigned a temporary URN {urn}. Your uploaded files have been submitted for processing. Further uploads have been disabled until processing completes. All other fields are freely editable. You will be able to publish this Score Set once successfully processed. Once published, your submission will be assigned a permanent URN and editing will be limited to a select number of fields.
