### ISSUE TITLE
Expt set/Expt/Score Set hierarchies in tables

### ISSUE THREAD

**Issue by mulescent** [FowlerLab/mavedb#65]
Alan and I talked about this, but the current way of presenting expt sets/expts/score sets in tables is really unintuitive.  It's nearly impossible to know which is which (you have to read the URN and know how it is formatted), and consequently tough to know what to click on.

I suggest one of the following:

*Reformatting so that search only shows the highest-level results in a hierarchy (e.g. just an expt set or expt, in most cases).  

*Showing score sets/expts using an expandable button for each expt set/expt

*Changing the table so that the hierarchy is clear (e.g. by addinga new column that explicitly says what each row represents)

**Comment by daniaki** [comment]
I've implemented option 2:

![nested](https://user-images.githubusercontent.com/7043686/45010368-86c91f00-b050-11e8-8c2d-6b7d28f1dea5.png)

`Scoresets` will appear as nested items under their parent `Experiment` with a small `+/-` icon on the far left to expand/collapse a row.
